MICRO_SWITCH_S1_NO_PIN       = 29
MICRO_SWITCH_S1_NC_PIN       = 31
MICRO_SWITCH_S2_NO_PIN       = 33
MICRO_SWITCH_S2_NC_PIN       = 35

RESET_PUSH_SWITCH_PIN        = 37

ON_BOARD_LED_PIN             = 36

POWER_LINE_DETECT_PIN        = 32

GPIO_3V3_1_PIN               = 38
GPIO_3V3_2_PIN               = 40

LCD_MODULE_ADDRESS          = 0x27
