MICRO_SWITCH_S1_NO_PIN       = 17
MICRO_SWITCH_S1_NC_PIN       = 27
MICRO_SWITCH_S2_NO_PIN       = 22
MICRO_SWITCH_S2_NC_PIN       = 18

RESET_PUSH_SWITCH_PIN        = 23

ON_BOARD_LED_PIN             = 24

POWER_LINE_DETECT_PIN        = 25

LCD_MODULE_ADDRESS          = 0x27
